import type { FeatureDetailContent } from "@/components/FeatureDetailModal";
export declare const volumeGenerationContent: FeatureDetailContent;
export declare const realTimeMonitoringContent: FeatureDetailContent;
export declare const antiDetectionContent: FeatureDetailContent;
export declare const multiWalletContent: FeatureDetailContent;
export declare const automatedTradesContent: FeatureDetailContent;
export declare const attractHoldersContent: FeatureDetailContent;
export declare const createFOMOContent: FeatureDetailContent;
export declare const performanceAnalyticsContent: FeatureDetailContent;
export declare const volumeDistributionContent: FeatureDetailContent;
export declare const tradingParametersContent: FeatureDetailContent;
export declare const antiDetectionTechnologyContent: FeatureDetailContent;
export declare const automatedOperationContent: FeatureDetailContent;
export declare const solArchitectureContent: FeatureDetailContent;
export declare const featureDetailsMap: {
    "Volume Generation": FeatureDetailContent;
    "Real-time Monitoring": FeatureDetailContent;
    "Anti-Detection System": FeatureDetailContent;
    "Multi-Wallet Support": FeatureDetailContent;
    "Automated Multithreaded Trades": FeatureDetailContent;
    "Attract New Holders & Whales": FeatureDetailContent;
    "Create FOMO & Trending Status": FeatureDetailContent;
    "Real-Time Performance Analytics": FeatureDetailContent;
    "Strategic Volume Distribution": FeatureDetailContent;
    "Customizable Trading Parameters": FeatureDetailContent;
    "Anti-Detection Technology": FeatureDetailContent;
    "24/7 Automated Operation": FeatureDetailContent;
    "SOL-Optimized Architecture": FeatureDetailContent;
};
