[build]
command = "npm install && npm run build && cp -r client/dist dist"
publish_directory = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200