[build]
builder = "nixpacks"
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "npx serve -s dist"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10

[deploy.env]
NODE_ENV = "production"
PORT = "3001" 