# Cloudflare Pages configuration
[build]
command = "cd client && npm run build"

# Environment variables section
[build.environment]
NODE_VERSION = "20"

# Site configuration
[site]
bucket = "dist"

# Pages configuration
[pages]
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.upload]
format = "service-worker"

[env.production]
name = "solvolume"
workers_dev = true
route = ""
zone_id = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.production.build]
command = "cd client && npm run build"

[env.production.build.upload]
format = "service-worker"

[env.production.site]
bucket = "dist" 