name = "solvolume"
main = "worker.js"
compatibility_date = "2023-08-01"

# For connecting the Worker to Cloudflare Pages
[site]
bucket = "./client/dist"

# KV storage configuration (optional)
# [[kv_namespaces]]
# binding = "CRYPTO_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# For scheduled tasks
[triggers]
crons = ["*/1 * * * *"] # Runs every minute

[build]
command = "cd client && npm install && npm run build"
publish = "client/dist"

[build.environment]
NODE_VERSION = "20"

[pages]
pages_build_output_dir = "client/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
workers_dev = true
route = "solvolume-94b.pages.dev/*"
zone_id = "your-zone-id"

[env.production.vars]
VITE_WS_URL = "wss://small-meadow-d788.comojaw412.workers.dev/ws" 