name = "solvolume"
main = "worker.js"
compatibility_date = "2023-08-01"

# KV storage configuration (optional)
# [[kv_namespaces]]
# binding = "CRYPTO_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# For scheduled tasks
[triggers]
crons = ["*/1 * * * *"] # Runs every minute

# Worker environment variables
[vars]
VITE_WS_URL = "wss://small-meadow-d788.comojaw412.workers.dev/ws"

[site]
bucket = "client/dist"

[env.production]
workers_dev = true
route = "small-meadow-d788.comojaw412.workers.dev/*"
zone_id = "your-zone-id"