# Cloudflare Pages configuration
[build]
command = "cd client && npm install && npm run build"
output_dir = "client/dist"

# Environment variables section
[build.environment]
NODE_VERSION = "18"

# Site configuration
[site]
bucket = "./client/dist"

# Pages Assets
[assets]
source = "client/dist"
destination = "/"

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Robots-Tag = "index, follow"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.cloudflareinsights.com; img-src 'self' data: blob: https:; connect-src 'self' https: wss:;"

# SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Cache configuration
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Pages specific configuration
[pages]
pages_build_output_dir = "client/dist"

[build.upload]
format = "service-worker"

[env.production]
name = "solvolume"
workers_dev = true
route = ""
zone_id = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.production.build]
command = "cd client && npm run build"

[env.production.build.upload]
format = "service-worker"

[env.production.site]
bucket = "dist" 