[build]
command = "cd client && npm install && npm run build"
publish = "client/dist"

[build.upload]
format = "service-worker"

[site]
bucket = "client/dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 