[build]
command = "npm run build"
publish = "dist"

[build.upload]
format = "service-worker"

[site]
bucket = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 