[build]
command = "npm run build"
pages_build_output_dir = "client/dist"

# Environment variables section
[build.environment]
NODE_VERSION = "20"

# Configure output directory for Pages
[site]
bucket = "./client/dist"
entry-point = "."

# Pages-specific configuration
[pages]
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Route all requests to index.html for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.upload]
format = "service-worker"

[env.production]
name = "solvolume"
workers_dev = true
route = ""
zone_id = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.production.build]
command = "npm run build"

[env.production.build.upload]
format = "service-worker"

[env.production.site]
bucket = "./client/dist" 