# Cloudflare Pages configuration
[build]
command = "npm run build"
cwd = "."
pages_build_output_dir = "dist"

# Environment variables section
[build.environment]
NODE_VERSION = "20"

# Site configuration
[site]
bucket = "./dist"
entry-point = "."

# Pages configuration
[pages]
compatibility_date = "2024-02-01"
compatibility_flags = ["nodejs_compat"]

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Robots-Tag = "index, follow"

# SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.upload]
format = "service-worker"

[env.production]
name = "solvolume-prod"
route = "solvolume.com/*"
workers_dev = true
zone_id = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.production.build]
command = "cd client && npm run build"

[env.production.build.upload]
format = "service-worker"

[env.production.site]
bucket = "dist"

[env.staging]
name = "solvolume-staging"
route = "staging.solvolume.com/*"

[env.development]
name = "solvolume-dev"
route = "dev.solvolume.com/*" 