[build]
command = "npm run build"
pages_build_output_dir = "client/dist"

# Environment variables section
[build.environment]
NODE_VERSION = "20"

# Configure output directory for Pages
[site]
bucket = "client/dist"

# Pages-specific configuration
[pages]
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Route all requests to index.html for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200 