# Cloudflare Pages configuration
[build]
command = "cd client && npm install --legacy-peer-deps && npm run build"
cwd = "."

# Environment variables section
[build.environment]
NODE_VERSION = "20"

# Site configuration
[site]
bucket = "client/dist"

# Pages configuration
[pages]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Robots-Tag = "index, follow"

# SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
name = "solvolume"
workers_dev = false
route = "solanavolumebot.io/*"
zone_id = "your-zone-id"

[env.production.vars]
ENVIRONMENT = "production"

[env.production.site]
bucket = "client/dist" 