$content = @'
[build]
command = "cd client && npm install && npm run build"
publish = "client/dist"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "client/dist"

[pages]
pages_build_output_dir = "client/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
workers_dev = true
route = "solvolume-94b.pages.dev/*"
zone_id = "your-zone-id"

[env.production.vars]
VITE_WS_URL = "wss://small-meadow-d788.comojaw412.workers.dev/ws"
'@

[System.IO.File]::WriteAllText("wrangler.toml", $content, [System.Text.Encoding]::UTF8)